# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Front matter defaults for posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      date_format: "%Y%m%d"
      read_time: true
      enable_copy_code_button: true
      comments: true
      share: true
      related: true

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Enable Lunr search
search: true
lunr:
  search_within_pages: true

# Site navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/

# This will produce page titles like Sample Page | My Awesome Site.
title_separator: "|"

# description for doc head meta (for Google Search) and in feed.xml site desc.
description: "Personal page for 李良澤 Josh Lee."

# Author settings
cnname: &cnname "李良澤"
enname: &enname "Josh Lee"

# Title on browser tab
title: "李良澤 Josh Lee"
# Title on top of page
masthead_title: *cnname
# Subtitle just below title
subtitle: *enname
# On bottom of page
name: *enname

author:
  name: "Josh Lee"
  avatar: "/assets/images/headshot_cornell.jpg"
  bio: "Applied Research at Google DeepMind.\nOpinions my own."
  location: "San Francisco Bay Area"

author_profile: true

# Hide feed button
atom_feed:
  hide: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
