# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: &llzname "李良澤 Josh Lee"
email: "me@llz.info"

# This will produce page titles like Sample Page | My Awesome Site.
title_separator: "|"

# the subpath of site, e.g. /blog
baseurl: ""

# the base hostname & protocol for site, e.g. http://example.com
url: "http://llz.info"

# A short tagline that appears below the title in site masthead.
subtitle: ""

# Site author name which can be overriden on specific pages.
name: *llzname

# description for doc head meta (for Google Search) and in feed.xml site desc.
description: "Personal page for 李良澤 Josh Lee."

# twitter_username: jekyllrb
github_username:  "cterdam"

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "contrast"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
